### ISSUE TITLE
Will you post the instructions?

### ISSUE THREAD

**Issue by chengyu** [signorello/NDN.p4#1]
Hi,

Will you post the instructions on how to repeat the demo?

Thanks,

**Comment by signorello** [comment]
Hi,
I have just uploaded the doc and files I add on my machine, but those need to be tested on a freshly new installation to be sure that I have not missed anything. I will do it asap.
Thank for you interest

**Comment by chengyu** [comment]
Thanks, please also point out which mini-ndn you are using.

**Comment by signorello** [comment]
Mininet and mini-ndn versions have been included in the main README file.
You're welcome.

**Comment by chengyu** [comment]
More questions:
1. where should I put the p4-switch.conf? minindn home directory?
2. you mentioned "Configuration file for NFD", but there is no such file in the repo
3. No "p4.ndn.basic.conf" in the repo
4. after compile the p4 code, where should the json code go?

**Comment by signorello** [comment]
Thank you a lot for pointing those out and sorry for the imprecise instructions and the missing files. Follow the answers point-by-point:
1 yes, the p4-switch.conf goes to the minindn home dir (this will be clarified in the README too)
2-3 I have committed the two missing files
4 the json file can be put anywhere as long as the path is rightly specified in p4-switch.conf

**Comment by chengyu** [comment]
just resume to test it, find two issues:
1. the modified mini-ndn is hard-coded the path to p4-switch.conf (/usr/local/src/mini-ndn/p4-switch.conf), and it is not installed on my OS in the same directory. I have to change it manually
2. The experiment failed, because the NFD cannot be connected, could you give me some hints on how to fix it?

NFD is not running ….
I don't start the application
I don't start the application
Loading experiment: P4_NDN_experiment
Failed to get nfd-status after 10 attempts on host a
Traceback (most recent call last):
  File "bin/minindn", line 423, in <module>
    execute(options)
  File "bin/minindn", line 401, in execute
    experiment.start()
  File "/usr/local/lib/python2.7/dist-packages/Mini_NDN-0.1.1-py2.7.egg/ndn/experiments/my_experiment.py", line 30, in start
    self.setup()
  File "/usr/local/lib/python2.7/dist-packages/Mini_NDN-0.1.1-py2.7.egg/ndn/experiments/my_experiment.py", line 51, in setup
    raise AssertionError(res1)
AssertionError: error while connecting to the forwarder (No such file or directory)

**Comment by signorello** [comment]
Thanks for catching point one, I fixed it and added sth to the main README to specify the right path to the p4-switch.conf .
As regards point 2, I would suggest to check the following steps before any further investigation:
a) before running the mini-ndn experiment check that the nfd daemon starts and runs successfully on your system from outside mininet. If not, there is no way you can get it running properly within minindn either.
b) I've had some problems with the nfd.conf whose format has evolved. In fact, a newer version of the nfd daemon was crashing because of an unrecognized string in that configuration file which I had imported from a system where an older nfd version had been installed and used. I am going to open an issue about this, hoping to figure out the best way to fix asap. In the meantime, a quick and dirty solution is that you copy the template file provided with the NFD installed on your system (usually called $SOME_PATH/nfd.conf.sample) and apply manually a few changes to that file. The changes consists to disable ipv6 channels for both TCP and UDP in the "face_system" section of the nfd.conf.

c) if the previous two points don't give you any hint, check the nfd log of the nodes involved in the experiment which is written to /tmp/{a,b}/{a,b}.log
